apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.configmap_name }}
data:
  MYSQL_DATABASE: {{ .Values.configmap.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.configmap.MYSQL_USER }}
  DB_HOST: db
  DB_PORT: "{{ .Values.configmap.DB_PORT }}"
  REDIS_USER: {{ .Values.configmap.REDIS_USER }}
  AUTH_HOST: auth
  AUTH_PORT: "{{ .Values.configmap.AUTH_PORT }}"
  WEATHER_PORT: "{{ .Values.configmap.WEATHER_PORT }}"
  WEATHER_HOST: weather
  REDIS_HOST: redis

